CREATE TABLE profile(

	id 				BIGSERIAL 			PRIMARY KEY,		
	email 			CHAR(255) 			NOT NULL			UNIQUE,
	title			CHAR(255)   		NOT NULL,
	first_name 		CHAR(255) 			NOT NULL,
	last_name		CHAR(255) 			NOT NULL,
	full_name		CHAR(255) 			NOT NULL,
	password		CHAR(255) 			NOT NULL,
	has_agreed		BOOLEAN 			NOT NULL 			DEFAULT FALSE,
	member_type 	CHAR(255)       	NOT NULL,
	street_address	TEXT				NOT NULL,
	state 			CHAR(255)   		NOT NULL,
	city			CHAR(255)			NOT NULL,
	date_of_birth	DATE 				NOT NULL,
	personal_email	CHAR(255),
	bank_state		CHAR(255)   		NOT NULL,
	bank_branch		CHAR(255),
	bank_ifsc		CHAR(255),
	bank_name		CHAR(255),
	bank_city		CHAR(255),
	bank_account_number		CHAR(255),
	bank_account_type	CHAR(255),
	landline_std_code	INTEGER,
	landline_contact	BIGINT,
	mobile_contact		BIGINT			NOT NULL,
	alternate_mobile_contact	BIGINT,
	zip_code			INTEGER			NOT NULL,
	other_comments		TEXT,
	is_staff			BOOLEAN			NOT NULL			DEFAULT FALSE,
	is_active			BOOLEAN			NOT	NULL			DEFAULT FALSE,
	referral_code		CHAR(255),
	created_at			TIMESTAMP WITH TIME ZONE			NOT NULL	DEFAULT now(),
	updated_at			TIMESTAMP WITH TIME ZONE			NOT NULL	DEFAULT now()

);
